### ISSUE TITLE
hitmaps vs wcov from TOAST

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4mapbasedsims#10]
@keskitalo 
I am comparing the hitmap and the white noise covariance matrices the design tool gets from TOAST,
if I try to compute the white noise covariance matrix myself from the NET and the hitmap,
first, I see masked pixels in the wcov which are not masked in the hitmap, then I get a disagreement around 5% on the value itself:
https://gist.github.com/91892199de3f71d048fc47377619aed6

is this expected? is there anything else that goes into the white noise covariance matrix?

**Comment by zonca** [comment]
better rendered in nbviewer: https://nbviewer.jupyter.org/gist/zonca/91892199de3f71d048fc47377619aed6

**Comment by keskitalo** [comment]
This is expected. The white noise matrices are used in decoupling IQU from the polarization-modulated detector data. If the pixels are unevenly observed, that decoupling may not be possible, or the uncertainty in IQU is correlated, amplifying the noise levels.

**Comment by zonca** [comment]
but I find lower noise in the wcov compared to NET + hitmaps, added mean and median at the bottom of https://nbviewer.jupyter.org/gist/zonca/91892199de3f71d048fc47377619aed6

**Comment by keskitalo** [comment]
The simulation pipeline modulates the NETs according to the observing elevation. For South Pole, the simulated noise depth depends on the declination.

**Comment by zonca** [comment]
thanks @keskitalo 
so I'll stop using hitmaps and directly use wcov for spectra. also mentioned in docs, see attached commit to this issue.
