### ISSUE TITLE
Run noise-only and atmosphere-only maps

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4mapbasedsims#16]
Currently we create noise+atmosphere maps.
For verification and comparison, it is useful to have them separate.
Running noise only, first for LAT

**Comment by zonca** [comment]
@keskitalo I have launched noise only, LAT, with no splits,
results will be appearing in the next hours at:

    /global/cscratch1/sd/zonca/cmbs4/map_based_simulations/202102_design_tool_run/noise

the noise sims produce also hitmaps and wcov so are quite slow, I launched also atmosphere only, it should finish earlier:

    /global/cscratch1/sd/zonca/cmbs4/map_based_simulations/202102_design_tool_run/atmo

**Comment by zonca** [comment]
ok @keskitalo those are completed,
I deleted hitmaps and wcovs, as they are duplicates.

**Comment by keskitalo** [comment]
Thanks! These very very helpful in identifying the source of excess noise.
