### ISSUE TITLE
Increase in small scale dust/sync power

### ISSUE THREAD

**Issue by sriniraghunathan** [CMB-S4/s4mapbasedsims#18]
The attached plot shows the (Gaussian) beam deconvolved EE power spectrum using the latest set of pySM dust simulations. Solid lines are actual power while dash-dotted lines are a power law fit to 278 GHz and then scaled to other bands assuming Td = 20 K and beta = 1.54. 

I am confused about the increase in small scale power in the simulations (solid lines). Synchrotron also has the same behaviour but not shown here. 

Cl are calculated using `H.anafast` which are then divided by `Bl^2` to take beam into account. 
(I am also downgrading the simulations from Nside=4906 to 2048 but have not yet carefully checked if that can cause serious issues.)

Could you look into this and tell me if I am doing anything silly? 

![image](https://user-images.githubusercontent.com/3856456/116291573-976ebc00-a749-11eb-8ee6-46c0513c2f76.png)

**Comment by zonca** [comment]
My first idea is that there is some error in how you apply the beam deconvolution.
can you doublecheck that or paste the relevant code here?
it could even be that your beam deconvolution is fine but you are amplifying the noise that is in the input dust templates (from Planck).

**Comment by zonca** [comment]
or did you do the same in previous releases and there it was working fine?

**Comment by sriniraghunathan** [comment]
This is all I am doing. The issue is present in the previous release as well. I just checked.
`cl = H.anafast(map1, map2, lmax)
bl = H.gauss_beam(np.radians(beam_in_arcmins/60.), lmax)
cl = cl / bl**2.
`

**Comment by zonca** [comment]
* are you using beams for here? https://github.com/CMB-S4/s4mapbasedsims/blob/master/202102_design_tool_run/instrument_model/cmbs4_instrument_model.tbl
* was this different in earlier releases?

**Comment by sriniraghunathan** [comment]
Yeah the beam values seem right. 

If Planck noise is blowing up due to beam deconvolution, should I just null modes where the ratio of output beam in the ILC (nominally 1.4 arcmins) and the individual beams is above a certain threshold?
`null_inds = np.where( (bl_fid / bl_band) >= threshold )` or something like that?

![S4_Chilean_LAT_beams](https://user-images.githubusercontent.com/3856456/116314002-64392680-a763-11eb-9ad2-509475c36699.png)

**Comment by zonca** [comment]
yes, right, I don't know if there is a standard way of deciding the threshold

**Comment by sriniraghunathan** [comment]
From the figure, it seems that the data (solid lines) deviate from the fits (dash-dotted lines) close to \ell ~ 2000 for 27/39 GHz. Those beams are so large that the power is already down there by 20% (40%) for the two respectively. 

But I agree any number chosen as threshold is only arbitrary and can **only be a temporary fix**.

**Comment by sriniraghunathan** [comment]
For Neff/cluster forecasts, we are currently performing ILC using power spectra and not with actual maps. **So a better temporary solution would be to simply assume the fits (dash-dotted) to be the actual dust power spectra**. What do you think?
