### ISSUE TITLE
CMB-only simulations for Data Challenge 1

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4mapbasedsims#19]
[DC1](https://cmb-s4.atlassian.net/wiki/spaces/XPI/pages/237764628/Data+Challenge+1) will only need CMB input maps, no foregrounds.

I will use `mapsims` to prepare beam-convolved CMB maps, NSIDE 4096 / 512.

In the design tool sims (https://github.com/CMB-S4/s4mapbasedsims/tree/master/202102_design_tool_input#combined-maps-inputs-for-the-design-tool) we had 3 CMB maps:

* `cmb_lensing_signal`: `cmb` minus `cmb_unlensed`
* `cmb_unlensed_solardipole`: `cmb_unlensed` with dipole removed, plus the Planck HFI 2018 solar dipole map
* `cmb_tensor`

here we will have just 1 which includes CMB scalar, tensor, lensing and solar dipole.

We also need to have a version of the CMB map with "beyond vanilla" cosmology with N_eff = 3.146 (I need to update the status of this at https://github.com/simonsobs/so_pysm_models/issues/55, Alex sent me via email the results).

Then we also need a CMB map with no tensor components.

So @keskitalo @jdborrill, we should have 3 CMB maps, right?

**Comment by jdborrill** [comment]
For Phase 1 we're using a single CMB sky with r = D(N_eff) = 0.

For Phase 2 we will add r = 0.003 and D(N_eff) = 0.06 (and any other
cosmological parameter changes this implies).

Julian

**Comment by zonca** [comment]
thanks @jdborrill,
@keskitalo can you please confirm 1 map which includes solar dipole and lensed scalar CMB with same parameters of the design tool run is fine?

**Comment by keskitalo** [comment]
Yes, one map per channel.

The cosmological parameters at https://mocks.cita.utoronto.ca/data/websky/v0.0/cosmology.py seem fine to me. However, there is no mention of curvature OR cosmological constant. I presume curvature is zero and Omega_Lambda = 1 - Omega_m.

**Comment by keskitalo** [comment]
Yes, and apologies for dropping the ball on the original question.

**Comment by zonca** [comment]
Nice! so I'm done, here the maps:

https://github.com/CMB-S4/s4mapbasedsims/tree/master/202102_design_tool_input#combined-maps-inputs-for-the-design-tool
