### ISSUE TITLE
DC-0 Validation spectra: Dust

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4mapbasedsims#28]
@giuspugl I am looking rough spectra of DC-0 inputs for validation purposes. These are unmasked full sky anafast spectra up to 2.5 * ellmax.

I noticed a drop around ell=2000 in dust `d10` in all channels, worse at low frequencies:

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/87a0e868-f2fe-4944-b99c-bc72bdf77e94)

What is strange is that this does not show up in `d9`, which has the same templates.

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/80b34784-adeb-43cd-864c-9229fc0a93ca)

so it must be coming from dust temperature or spectral index?

I haven't transferred the maps to NERSC yet, will post here when I do.

**Comment by zonca** [comment]
Polarization looks fine:

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/ebc31748-3b86-4e77-b61d-bcba52612af2)

**Comment by jdborrill** [comment]
Did this (and the synchrotron) issue not show up in the SO sims for the
same sky models you ran a month ago, Andrea?

J

**Comment by zonca** [comment]
@jdborrill the synchrotron issue yes, see https://github.com/simonsobs/map_based_simulations/issues/44#issuecomment-1481586936. I asked if someone else could investigate the issue on the Penexp call and on Slack https://simonsobs.slack.com/archives/CE44LGAAK/p1679592345528889.

About dust, I also noticed it, see https://nbviewer.org/gist/zonca/7026e5f4fd9ef304a89f1c171e43f2ce, I didn't flag it because I assumed it was due to how we generate small scales. Also now I think the same, but if someone else also looks at it better. And anyway it is better to flag it.

**Comment by giuspugl** [comment]
it might be related to spectral indices indeed, @zonca  the spectra param. maps should be  produced at ellmax=2000  (this was because of testing purposes but we should have kept the same ellmax as the amplitude maps.  therefore small scales behave differently at different multipoles and different freq., this is why we do see a clear glitch .

**Comment by zonca** [comment]
thanks @giuspugl, I will look into this.

**Comment by zonca** [comment]
confirm there is an issue both in beta and Td, templates are unaffected

## Beta at 2048 and 4096

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/2b40e642-509b-4da0-a595-b4a68a020100)

## Td at 2048 and 4096

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/df38b06d-6734-48a8-819c-4ac76ab9f2eb)

## Templates 2048 and 4096

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/b35a787d-2e82-4048-88c6-0851e9221edc)

**Comment by zonca** [comment]
Synchrotron beta looks fine

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/88556005-b863-4058-9a35-6c9bb79e57e1)

**Comment by zonca** [comment]
it was a bug in the notebook that generates the spectrum of the small scales, it was using Lmax=2048 instead of 16384.
now:

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/ba2203c1-b0e7-41f5-8ddd-08fabd4ffe65)

**Comment by zonca** [comment]
I am regenerating the beta and Td maps at all resolutions, after we figure out the synchrotron issue, I'll release 3.4.0b9 and rerun the updated models.

**Comment by zonca** [comment]
## Comparison of spectra before and after

> confirm there is an issue both in beta and Td, templates are unaffected
> 
> ## Beta at 2048 and 4096
> ![image](https://user-images.githubusercontent.com/383090/243873998-2b40e642-509b-4da0-a595-b4a68a020100.png)

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/3ed1f629-b855-49fc-b4e5-ca716dbe3b8d)

> ## Td at 2048 and 4096
> ![image](https://user-images.githubusercontent.com/383090/243874175-df38b06d-6734-48a8-819c-4ac76ab9f2eb.png)

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/97456118-7cb2-403a-8978-79edfe8be1a3)

**Comment by giuspugl** [comment]
This is great! thanks a lot @zonca  for addressing this!

**Comment by zonca** [comment]
this is going to be fixed in `3.4.0b9`

**Comment by zonca** [comment]
ok, the verification spectra are fine now:

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/ab09a8ef-9070-497a-a47b-406046a8261b)
