### ISSUE TITLE
Check beam smoothing in dc-0

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4mapbasedsims#34]
Need to double check beam smoothing in DC-0, @keskitalo do you have any pointer on what could be wrong?

**Comment by zonca** [comment]
first of all let's check inputs, @smsimon could you please check that the beams in the parameter file are fine?
https://github.com/CMB-S4/s4mapbasedsims/blob/main/202305_dc0/instrument_model/cmbs4_instrument_model.tbl

**Comment by smsimon** [comment]
Beam sizes look correct there

**Comment by zonca** [comment]
@keskitalo is seeing the problem in CMB, I can compare the input CMB power spectrum smoothed with the beam to the dc-0 map based simulations and check if they agree.

**Comment by zonca** [comment]
compare the SAT

**Comment by zonca** [comment]
ok, compared some of the SATs, they seem fine @keskitalo 

![SAT_f040](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/51bd7087-6d4b-4a49-8a7e-808554b138fe)
![SAT_f145](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/c4d02b50-3645-4797-b2b7-b743aba9f671)
![SAT_f280](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/ba3bca82-70d9-4c6c-beb9-2d325a4a83f4)
![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/1e1934a5-6bae-489f-b89a-880c7f325906)

anything specific I should check?

[the notebook](https://gist.github.com/zonca/3f1a691f4913dd58410979e829058e7d)
