### ISSUE TITLE
Foreground simulation for CMB-S4 Phase 1 Chile simulations

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4mapbasedsims#35]
We need PanEx medium complexity galactic foregrounds with the latest instrument model.

@smsimon has there been any change in the instrument model compared to dc0 (https://github.com/CMB-S4/s4mapbasedsims/blob/main/202305_dc0/instrument_model/cmbs4_instrument_model.tbl)?

**Comment by zonca** [comment]
@smsimon if you are not sure I can just extract again from `s4sim` and compare myself.

**Comment by smsimon** [comment]
Yes, I am working on implementing LAT changes (adding the 20 GHz band to the CHLATs and changing the focal plane layout) and the SAT will be completely different.

**Comment by smsimon** [comment]
@zonca The beams are now incorporated into s4sim. The toml file is here: https://github.com/CMB-S4/s4sim/blob/master/chile_optimization_sims/phase1/hardware.toml.gz

**Comment by zonca** [comment]
thanks @smsimon, I am using this exact version of that file:
https://github.com/CMB-S4/s4sim/blob/466487dd39e6c099bac821930ba2d6352f21c4f3/chile_optimization_sims/phase1/hardware.toml.gz

**Comment by smsimon** [comment]
@zonca The updated one in the Phase I tag of the code is the best to use, but the only difference with that one is that there was an error in the elevation noise scalings. Note that the noises here for the CHLATs are referenced at 50 deg elevation vs. the usual 40 deg elevation that we have used in the past

**Comment by zonca** [comment]
@smsimon great, that is better, so I'll use:

https://github.com/CMB-S4/s4sim/blob/Phase1/chile_optimization_sims/phase1/hardware.toml.gz

**Comment by zonca** [comment]
@smsimon such a big TOML file takes almost 2 minutes to parse in Python, so I am going to extract just the values I need and create my own instrument model.
We are still using tophat bandpasses, right?

**Comment by zonca** [comment]
@smsimon I still see `SPLAT` channels, should I simulate those?

**Comment by smsimon** [comment]
No need for this

**Comment by zonca** [comment]
@smsimon We are still using tophat bandpasses, right?

**Comment by smsimon** [comment]
Right

**Comment by zonca** [comment]
@smsimon thanks, can you please review the difference between the old and the new instrument model? Just the 1 file pointed here

https://github.com/CMB-S4/s4mapbasedsims/pull/36/commits/7a04c31ffbd0c60a6c232971c1be2c75204336b6#diff-4254ad9eeb71e0d4a181d7d47f996bba3a5a14d921cb8c3f94d7418ce3951cc9

**Comment by smsimon** [comment]
This looks okay to me

**Comment by zonca** [comment]
executing in https://github.com/CMB-S4/s4mapbasedsims/pull/36
