### ISSUE TITLE
polarized dust doesn't show up correctly in SAT output foreground maps

### ISSUE THREAD

**Issue by cbischoff** [CMB-S4/s4mapbasedsims#4]
* Load HFS-2 (270 GHz LAT) input dust map from `dstool/input_pysm/512/dust/0000/cmbs4_dust_uKCMB_SAT-HFS2_nside512_0000.fits`
* Load HFS-2 output foreground map from `dstool/output/s4_reference_design_foregrounds/SAT-HFS2_pole/cmbs4_KCMB_SAT-HFS2_pole_nside512_1_of_1.fits` -- since we are at 270 GHz, this map should be primarily dust.
* Multiply both maps by the mask (`dstool/output/s4_reference_design_noise_atmo_7splits/SAT-HFS2_pole/cmbs4_hitmap_SAT-HFS2_pole_nside512_1_of_1.fits`), then visually compare the Q/U maps. There is no obvious visual correlation and the cross-spectrum between the two maps bounces around zero. The output Q/U foreground maps have ~3x larger amplitude with power weighted towards small scales.
* If I do the same input-vs-output comparison with the T maps, everything looks fine.
* If I do this comparison using the input synchrotron and output LFS-1 foreground map, there is a strong cross-correlation though the visual match is tricky because the input map has very large scale power that gets filtered out in mapmaking.

**Comment by keskitalo** [comment]
There seems to be something funny about the input maps. The dust input map is `/global/cscratch1/sd/zonca/cmbs4/map_based_simulations/202006_foregrounds_extragalactic_cmb_tophat/512/dust/0000/cmbs4_dust_uKCMB_SAT-HFS2_nside512_0000.fits` and, like you said, it should form the bulk of the combined foreground map at `/global/cscratch1/sd/zonca/cmbs4/map_based_simulations/202006_foregrounds_extragalactic_cmb_tophat/512/combined_foregrounds/0000/cmbs4_combined_foregrounds_uKCMB_SAT-HFS2_nside512_0000.fits`.

Here are some standard deviations measured in `dust` and `combined_foregrounds`:
```                                               
                            |  full sky                     |   SAT HFS2 patch
                            |   I     |     Q    |     U    |   I     |     Q    |     U    |
dust                        |  3241   |   59.3   |   28.0   |  131.1  |    6.3   |    5.4   |
combined_foregrounds        |  3309   |   61.1   |   31.5   |  138.1  |   15.7   |   15.4   |
combined_foregrounds - dust |  93.9   |   14.4   |   14.4   |   17.7  |   14.4   |   14.4   |
```

So the combined foreground polarization in the SAT patch at HFS2 is dominated by something entirely different than dust. What do you think it is @zonca ?

**Comment by keskitalo** [comment]
Found it! The CIB component in `/global/cscratch1/sd/zonca/cmbs4/map_based_simulations/202006_foregrounds_extragalactic_cmb_tophat/512/cib/0000/cmbs4_cib_uKCMB_SAT-HFS2_nside512_0000.fits` has exactly same map in the I, Q and U columns of the FITS file. The standard deviation also matches the 14.4uK excess we saw above.

**Comment by zonca** [comment]
sorry, I noticed something in the CIB, see https://github.com/CMB-S4/s4mapbasedsims/issues/3, but haven't investigate yet.

**Comment by zonca** [comment]
there was a wrong broadcasting, so CIB which is T only was replicated on polarization as well.

I have rerun the SAT and generated CIB and the combined map again, can you please rerun your checks on these?
Currently are on my scratch, if they are fine I'll run on LAT and copy to the project folder.

```
/global/cscratch1/sd/zonca/cmbs4/map_based_simulations/202006_foregrounds_extragalactic_cmb_tophat/512/cib/0000
/global/cscratch1/sd/zonca/cmbs4/map_based_simulations/202006_foregrounds_extragalactic_cmb_tophat/512/combined_foregrounds/0000
```

**Comment by cbischoff** [comment]
Yes, this looks much improved. Just to check, the CIB component is now totally unpolarized?

**Comment by zonca** [comment]
Yes, Q and U are 0 arrays

**Comment by keskitalo** [comment]
The new Pole SAT maps are here: `/global/cscratch1/sd/keskital/s4sim/reference_tool/out_v2`.

**Comment by zonca** [comment]
ok, I regenerated the `foregrounds` outputs at: `/global/cscratch1/sd/zonca/cmbs4/s4refsimtool/s4_reference_design_foregrounds`

if they are fine I'll copy to project

**Comment by keskitalo** [comment]
@zonca When will you have the LAT foreground maps prepared?

**Comment by zonca** [comment]
I'm trying on Jupyter, if that works, tonight, if not, Monday night

**Comment by zonca** [comment]
@keskitalo ok, LAT maps are available at `/global/cscratch1/sd/zonca/cmbs4/map_based_simulations/202006_foregrounds_extragalactic_cmb_tophat/4096/combined_foregrounds/0000`

**Comment by keskitalo** [comment]
All of the filtered foreground maps can be found here: /global/cscratch1/sd/keskital/s4sim/reference_tool/out_v2

**Comment by zonca** [comment]
thanks @keskitalo 

LAT output maps are at `/global/cscratch1/sd/zonca/cmbs4/s4refsimtool/s4_reference_design_foregrounds`

I will run some validation and then copy everything to project, please write here if you have any more feedback.

**Comment by jdborrill** [comment]
Just to get us all in the right habits, we're actually running verification
(did we do the thing right) on the maps now,  not validation (did we do the
right thing).

Julian

**Comment by zonca** [comment]
@jdborrill correct, thanks

**Comment by zonca** [comment]
updated `/global/project/projectdirs/cmbs4/dm/dstool/input_pysm` with the LAT and SAT fixed `cib` and `combined_foregrounds`

**Comment by zonca** [comment]
added `gnomview` plots to check consistency of input and output foregrounds: https://github.com/CMB-S4/s4mapbasedsims/blob/master/202006_reference_design/plot_gnomview/README.md

**Comment by zonca** [comment]
ok, this is completed, I posted link to the DM reference sims docs on the sim and analysis logbook: https://cmb-s4.org/wiki/index.php/Simulation_and_Forecasting_Logbook#Logbook_Entries_.28reverse_chronological.29
